import { NextRequest, NextResponse } from 'next/server';

/**
 * WebHarvest Intelligent Asset & SPA Route Middleware
 * 
 * Intercepts root-relative asset requests (e.g. /vuexy-vuejs-admin-template/..., /assets/..., /images/...)
 * generated by mirrored Single Page Applications (Vue, React, Next.js, Vite) and seamlessly
 * rewrites them to the appropriate mirror preview API route (/api/mirror/[id]/preview/...).
 * 
 * This completely prevents 404 blank screens when previewing mirrored SPAs.
 */
export function middleware(req: NextRequest) {
  const { pathname, search } = req.nextUrl;

  // 1. Skip internal Next.js paths, API routes, and top-level pages
  if (
    pathname.startsWith('/_next') ||
    pathname.startsWith('/api') ||
    pathname.startsWith('/mirror') ||
    pathname === '/' ||
    pathname === '/favicon.ico'
  ) {
    return NextResponse.next();
  }

  // 2. Identify target mirror job ID from:
  // a) Referer header (when iframe requests sub-resources)
  // b) webharvest_preview_id cookie (set during preview visit)
  let targetId: string | null = null;

  const referer = req.headers.get('referer');
  if (referer) {
    const match = referer.match(/\/api\/mirror\/([a-zA-Z0-9]+)\/preview/);
    if (match && match[1]) {
      targetId = match[1];
    } else {
      const mirrorMatch = referer.match(/\/mirror\/([a-zA-Z0-9]+)/);
      if (mirrorMatch && mirrorMatch[1]) {
        targetId = mirrorMatch[1];
      }
    }
  }

  if (!targetId) {
    const cookie = req.cookies.get('webharvest_preview_id');
    if (cookie && cookie.value) {
      targetId = cookie.value;
    }
  }

  // 3. If a mirror ID is identified, rewrite the request internally to the preview handler
  if (targetId) {
    const cleanPath = pathname.startsWith('/') ? pathname.slice(1) : pathname;
    const rewriteUrl = new URL(`/api/mirror/${targetId}/preview/${cleanPath}${search}`, req.url);
    
    return NextResponse.rewrite(rewriteUrl);
  }

  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!_next/static|_next/image|favicon.ico).*)',
  ],
};
