services:
  - type: web
    name: webharvest
    runtime: node
    plan: free
    buildCommand: npm install && npx playwright install chromium chromium-headless-shell && npm run build
    startCommand: next start -H 0.0.0.0 -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: HOSTNAME
        value: 0.0.0.0
